### ISSUE TITLE
Remove the dynamically linked 'tool-sync' asset

### ISSUE THREAD

**Issue by chshersh** [chshersh/tool-sync#107]
Since we generate the statically linked binaries, we don't need the dynamically linked anymore. We couldn't remove them before because we needed the `v0.2.0` release. But it's okay to do the cleanup now 👍🏻 

Specifically,

- [ ] Remove the generation of dynamically linked assets

https://github.com/chshersh/tool-sync/blob/df7d4768c9cff2a91616bd9686bc928a52fc8c10/.github/workflows/release.yml#L26-L29

- [ ] Change the name for the Linux OS to use statically linked builds

https://github.com/chshersh/tool-sync/blob/df7d4768c9cff2a91616bd9686bc928a52fc8c10/src/sync/db.rs#L92

**Comment by jim4067** [comment]
Would like to look into this
