### ISSUE TITLE
Implement the '--path' option for the 'default-config' command

### ISSUE THREAD

**Issue by chshersh** [chshersh/tool-sync#109]
Instead of outputting the config content, it should output the path to the default config location.

Relevant code parts:

* CLI argument type

https://github.com/chshersh/tool-sync/blob/df7d4768c9cff2a91616bd9686bc928a52fc8c10/src/config/cli.rs#L21-L22

* Running the command

https://github.com/chshersh/tool-sync/blob/df7d4768c9cff2a91616bd9686bc928a52fc8c10/src/lib.rs#L21

* Creating the path

https://github.com/chshersh/tool-sync/blob/df7d4768c9cff2a91616bd9686bc928a52fc8c10/src/lib.rs#L29-L44

**Comment by zixuanzhang-x** [comment]
Just to clarify, when the user type `tool default-config --path`, we should just print the path that gets returned by `resolve_config_path()`?

**Comment by chshersh** [comment]
@zixuanzhang-x Yes, you're correct, we should print only the path to stdout. But it shouldn't be the result of `resolve_config_path()`.

I propose to move the following part into a separate function like `get_default_config_path()` and use it in the `--path` option and in the `resolve_config_path()` functions.

```rust
match dirs::home_dir() { 
             Some(home_path) => { 
                 let mut path = PathBuf::new(); 
                 path.push(home_path); 
                 path.push(DEFAULT_CONFIG_PATH); 
                 path 
             } 
```
