### ISSUE TITLE
Upgrading dependencies other than clap

### ISSUE THREAD

**Issue by MitchellBerend** [chshersh/tool-sync#139]
Referencing #136

Other dependencies might also have released new versions but these still need to be checked.

- [ ] serde
- [ ] ureq
- [ ] zip
- [ ] console
- [ ] dirs
- [ ] flate2
- [ ] indicatif
- [ ] shellexpand
- [ ] tar
- [ ] tempdir
- [ ] toml

Edit: updated formatting

**Comment by jim4067** [comment]
Hello, 

I ran `cargo update` to update all the dependencies in the `cargo.toml`. 

All the tests are passing. Is this similar to what you wanted, or did you want to update the specified depencies above only?

**Comment by MitchellBerend** [comment]
@jim4067 I would prefer all the dependencies but there is already a pr for this issue actually. #140

**Comment by chshersh** [comment]
This has been resolved by @SanchithHegde in #140
