### ISSUE TITLE
Missing docstring on proxy flag

### ISSUE THREAD

**Issue by MitchellBerend** [chshersh/tool-sync#141]
https://github.com/chshersh/tool-sync/blob/5d1a6b6010ca44ec81571c4d7b677c3cb01bb6cd/src/config/schema.rs#L13-L21
https://github.com/chshersh/tool-sync/blob/5d1a6b6010ca44ec81571c4d7b677c3cb01bb6cd/src/config/cli.rs#L5-L17

The person who implemented this flag (me) forgot to add a doc strings to explain how to use this and what it does.
This option takes a proxy that can be understood by the [ureq Proxy](https://docs.rs/ureq/2.5.0/ureq/struct.Proxy.html) struct.

**Comment by jim4067** [comment]
let me look into this

**Comment by MitchellBerend** [comment]
Sure go ahead. I'm not sure what the doc string on this should be to be honest. I only know how to make the proxy work with my own set up.

The original issue is #82 and the pr is #121

**Comment by chshersh** [comment]
I would simply add a usage example, e.g.:

```
You can custom proxy in tool-sync like this:

tool --proxy=http://127.0.0.1:8080 sync
```
