### ISSUE TITLE
Provide more detailed TOML decoding errors

### ISSUE THREAD

**Issue by chshersh** [chshersh/tool-sync#25]
Currently, when TOML decoding fails due to missing fields or mismatched values, the error doesn't specify the missing field:

```
Error parsing configuration at path Cargo.toml: [Decode Error]
```

The corresponding function also simply returns `Option<Config>` instead of providing more details

https://github.com/chshersh/tool-sync/blob/950b4028a619d33303548acd06056949dcec1a4a/src/config/toml.rs#L48-L64

It would provide better UX to add more details to the `DecodeError` constructor in the `TomlError` type by telling all errors that happened during decoding:

https://github.com/chshersh/tool-sync/blob/950b4028a619d33303548acd06056949dcec1a4a/src/config/toml.rs#L10-L14

Open questions:

* Does the `toml` crate provide better decoding than `as_str()` and friends? All such functions return `Option<...>` while it would be better to have `Result<..., ...>`
* Does Rust have the analogue of the Haskell's `Validation` type to combine multiple errors and which can be used with `toml`?

**Comment by DukeManh** [comment]
Hey @chshersh, I ran into the same issue trying your tool. I'd like help with this.

**Comment by chshersh** [comment]
@DukeManh Sure, go for it!
