### ISSUE TITLE
Support path 'asset_name/bin/<exe_name>' inside assets

### ISSUE THREAD

**Issue by chshersh** [chshersh/tool-sync#54]
This is needed for some tools. Example:

* https://github.com/cli/cli/releases/tag/v2.14.7

All the search paths are specified here:

https://github.com/chshersh/tool-sync/blob/cb339b09238964e8dc2d1a72389b6624c5bb7599/src/sync/archive.rs#L144-L153

To fix this problem:

- [ ] Add one more path search entry
- [ ] Add tests for `gh`

**Comment by hgrahamcs** [comment]
Where are the current paths tested?

**Comment by chshersh** [comment]
@hgrahamcs Hmm, good question 🤔 

There're no tests for checking this function specifically. This issue came up when I tried downloading the GitHub CLI tool using `tool-sync`. So, the test would be:

- [ ] Add `gh` to the hardcoded database:

https://github.com/chshersh/tool-sync/blob/eeed4bb786e5c95e45c41369f8d3d2a7c809200c/src/sync/db.rs#L5

- [ ] Add `gh` to the `full-database.toml` test

https://github.com/chshersh/tool-sync/blob/main/tests/full-database.toml

- [ ] Add tests on the CI

* https://github.com/chshersh/tool-sync/blob/eeed4bb786e5c95e45c41369f8d3d2a7c809200c/.github/workflows/ci.yml#L77-L82
* https://github.com/chshersh/tool-sync/blob/eeed4bb786e5c95e45c41369f8d3d2a7c809200c/.github/workflows/ci.yml#L98-L112

Adding `gh` to the database is something I wanted to do anyway as it's a quite popular tool so makes sense to add it 👍🏻

**Comment by MitchellBerend** [comment]
@hgrahamcs Are you still working on this?

**Comment by MitchellBerend** [comment]
@chshersh are the tasks in this issue still current or do I need to revise this fully?

**Comment by chshersh** [comment]
@MitchellBerend The tasks in the issue description and my previous comment are still current 👍🏻 

Feel free to take this issue. I'd like to release `tool-sync v0.2.0` this week and there're only a few issues left in the `v0.2.0` milestone.

**Comment by chshersh** [comment]
@MitchellBerend Unfortunately, `gh` has several assets matching the string `linux_amd64`:

* `gh_2.14.7_linux_amd64.deb`
* `gh_2.14.7_linux_amd64.rpm`
* `gh_2.14.7_linux_amd64.tar.gz`

So it's not enough to specify only this string. Try the following instead:

```toml
asset_name.linux = "linux_amd64.tar.gz"
```

The error message `[error] Unsupported asset type: gh_2.14.7_linux_amd64.deb ` is probably not clear as well so it could be improved, I guess. It means that `tool-sync` supports files only with the `.zip`, `.tar.gz` and `.exe` extensions and not `.deb`.

<hr>

The logic for finding the asset is here:

https://github.com/chshersh/tool-sync/blob/7700be2c33ca6619457b8dc90e9be5dc8d528ad3/src/model/tool.rs#L79-L84

So yes, it does find the first matching asset. It should be improved to find all and report an error early when several assets match the query string (or be smarter and actually select the one that matches). The only difficulty here is that in this mode all errors should be single-line to be present at the same line as the tool name. But proper error-reporting would require spanning an error message on multiple lines. So error-reporting improvement needs some thinking.

**Comment by MitchellBerend** [comment]
Okay I added the new path option but I also want to expand the scope of this issue to include that error message.
