### ISSUE TITLE
Consider install tools with Cargo

### ISSUE THREAD

**Issue by gillchristian** [chshersh/tool-sync#58]
This tool is awesome! Thanks for doing it! :bow: 

Would you consider support for installing tools with Cargo instead of the binaries?

I know this opens a can of worms, because now every other package manager should be supported as well. In that case maybe it could be some sort of plugin/configuration that tells `tool-sync` how to install a particular tool with a package manager.

I'd be willing to contribute such change as I install most of my tools with their corresponding package manager.

**Comment by chshersh** [comment]
Thanks for your kind words 🤗 

I learned recently about [cargo-binstall](https://github.com/cargo-bins/cargo-binstall/). Does it satisfy your need? It looks like the tool authors also have plans to support the installation directly from GitHub releases:

* https://github.com/cargo-bins/cargo-binstall/issues/4 

I have a separate issue to [add a more detailed comparison with cargo-binstall](https://github.com/chshersh/tool-sync/issues/56).

But at this point, the main goal of `tool-sync` is to download binaries from GitHub releases. The main reason for this is the fact that `tool-sync` supports not only Rust tools (while `cargo-binstall` focuses on Rust tools solely) and managing build tools for every language will be difficult 🥴

**Comment by gillchristian** [comment]
I don't think `cargo-binstall` would work for me, I basically install tools from source with Cargo (eg. `cargo install tool-sync`) or with any other package manager the tool is distributed with (be it `stack`, `yarn`, etc)

> managing build tools for every language will be difficult

My thought was that how the build tool works could be configured in the docs and expect the user to have it installed (or be part of the config). But I agree it it would be going in a different direction.

**Comment by chshersh** [comment]
@gillchristian I just learned about Clyde. It looks closer to what you're asking so maybe you can have a look whether it does what you want:

* https://github.com/agateau/clyde
