### ISSUE TITLE
Adding tag support in download progress output

### ISSUE THREAD

**Issue by MitchellBerend** [chshersh/tool-sync#63]
As discussed in #60 tag support is now actually possible from the start of the
process thanks to PR #61.

The max tag size can probably be passed to the formatter the same way the
`max_tool_size` is passed now. I can try and implement this but it might also
be a good first issue for others so they can familiarize themselves with the
code.

**Comment by chshersh** [comment]
Thanks for creating an issue! Feel free to try to implement this feature if you fell like it 🙂 

I've included it in the upcoming milestone and I think it would be great to do this feature.
