### ISSUE TITLE
Refactor custom 'display()' functions to use the 'Display' trait

### ISSUE THREAD

**Issue by chshersh** [chshersh/tool-sync#88]
See the discussion in #83 

The idea is to implement the [std::fmt::Display](https://doc.rust-lang.org/std/fmt/trait.Display.html) trait for data types where we already use a custom `display()` function. Specifically:

- [ ] `TomlError::display`
    * https://github.com/chshersh/tool-sync/blob/b79eeb91cfdc3a122e6693d503117f68ff1fb44e/src/config/toml.rs#L16-L24
- [ ] `ToolError::display`
    * https://github.com/chshersh/tool-sync/blob/b79eeb91cfdc3a122e6693d503117f68ff1fb44e/src/model/tool.rs#L20-L29
- [ ] `UnpackError::display`
    * https://github.com/chshersh/tool-sync/blob/b79eeb91cfdc3a122e6693d503117f68ff1fb44e/src/sync/archive.rs#L27-L37

Implementation example:

```rust
enum TestEnum {
    Var1(String),
    Var2(String),
}


impl fmt::Display for TestEnum {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TestEnum::Var1(s) => write!(f, "[VAR1]: {}", s),
            TestEnum::Var2(s) => write!(f, "[VAR2]: {}", s),
        }
    }
}
```

**Comment by zixuanzhang-x** [comment]
Sicne I just worked with implementing `Display` trait, this issue is probably a good one for me to get more familiar with the code base. If it's not taken then I'll start working on it?

**Comment by chshersh** [comment]
@zixuanzhang-x Sounds like an excellent next issue 🥇 

It's not taken. And I think @MitchellBerend will be really pleased when this one is done so we can unlock:

* #98
